### ISSUE TITLE
August 19 Milestone

### ISSUE THREAD

**Issue by aytona** [aytona/YogurtEndlessRunner#151]
### Main
- [x] The controller freezes after the Player gets an ice cube, or after playing the game for a while. Generally the controller goes back to normal if you JUMP.
- [x] The toppings need to be bigger, like 40%
- [x] The "landing dust" animation is cropping on the bottom
- [x] Make the "hitting red animation" 30% smaller
- [x] Implement the 3D background

### Others
- [x] #137 Background prefab needs to be completed

Have all of these ready by August 19

**Comment by aytona** [comment]
Scaled all toppings (not candy) up by 40%, and also added a scale factor on the script so each toppings can be scaled individually in the future.
